
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: emilianohg
author: Emiliano Hernández Guerrero
email: emilianohg2099@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Blog de programación en español
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://emilianohg.github.io" # the base hostname & protocol for your site
github_username:  emilianohg
permalink:        /blog/:year/:month/:day/:title.html


# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
